
import React from 'react';
import { 
  MessageSquare, 
  LayoutDashboard, 
  Network, 
  Calendar, 
  Send, 
  CheckCircle2, 
  Check,
  AlertCircle, 
  Download,
  Plus,
  Minus,
  Bot,
  User,
  Users,
  RefreshCw,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Zap,
  Target,
  TrendingUp,
  Wallet,
  FileText,
  Clock,
  Circle,
  Printer,
  Sun,
  Moon,
  Briefcase,
  Handshake,
  Sparkles,
  Shield,
  AlertTriangle,
  Lock,
  Unlock,
  PieChart,
  BarChart3,
  HelpCircle,
  ExternalLink,
  Building2,
  MoreHorizontal,
  Paperclip,
  X,
  Copy,
  Monitor,
  Server,
  Database,
  Cloud,
  Layers,
  Settings,
  Lightbulb,
  Grid3X3
} from 'lucide-react';

export const Icons = {
  Chat: MessageSquare,
  Dashboard: LayoutDashboard,
  Architecture: Network,
  Schedule: Calendar,
  Calendar: Calendar,
  Send: Send,
  Check: CheckCircle2,
  CheckMark: Check,
  Alert: AlertCircle,
  Download: Download,
  Plus: Plus,
  Minus: Minus,
  Bot: Bot,
  User: User,
  Users: Users,
  Refresh: RefreshCw,
  Down: ChevronDown,
  Up: ChevronUp,
  ChevronDown: ChevronDown,
  Zap: Zap,
  Target: Target,
  TrendingUp: TrendingUp,
  Wallet: Wallet,
  File: FileText,
  Clock: Clock,
  Circle: Circle,
  Printer: Printer,
  Sun: Sun,
  Moon: Moon,
  Briefcase: Briefcase,
  Handshake: Handshake,
  Sparkles: Sparkles,
  Shield: Shield,
  Warning: AlertTriangle,
  Lock: Lock,
  Unlock: Unlock,
  PieChart: PieChart,
  BarChart: BarChart3,
  Help: HelpCircle,
  Left: ChevronLeft,
  Right: ChevronRight,
  External: ExternalLink,
  Building: Building2,
  More: MoreHorizontal,
  Attach: Paperclip,
  Close: X,
  FileText: FileText,
  Copy: Copy,
  Monitor: Monitor,
  Server: Server,
  Database: Database,
  Cloud: Cloud,
  Layers: Layers,
  Settings: Settings,
  Lightbulb: Lightbulb,
  Grid: Grid3X3
};
