
import React from 'react';
import { 
  MessageSquare, 
  LayoutDashboard, 
  Network, 
  Calendar, 
  Send, 
  CheckCircle2, 
  Check,
  AlertCircle, 
  Download,
  Plus,
  Minus,
  Bot,
  User,
  Users,
  RefreshCw,
  ChevronDown,
  ChevronUp,
  Zap,
  Target,
  TrendingUp,
  Wallet,
  FileText,
  Clock,
  Circle,
  Printer,
  Sun,
  Moon,
  Briefcase,
  Handshake,
  Sparkles,
  Shield,
  AlertTriangle,
  Lock,
  Unlock,
  PieChart,
  BarChart3,
  HelpCircle
} from 'lucide-react';

export const Icons = {
  Chat: MessageSquare,
  Dashboard: LayoutDashboard,
  Architecture: Network,
  Schedule: Calendar,
  Calendar: Calendar,
  Send: Send,
  Check: CheckCircle2,
  CheckMark: Check,
  Alert: AlertCircle,
  Download: Download,
  Plus: Plus,
  Minus: Minus,
  Bot: Bot,
  User: User,
  Users: Users,
  Refresh: RefreshCw,
  Down: ChevronDown,
  Up: ChevronUp,
  Zap: Zap,
  Target: Target,
  TrendingUp: TrendingUp,
  Wallet: Wallet,
  File: FileText,
  Clock: Clock,
  Circle: Circle,
  Printer: Printer,
  Sun: Sun,
  Moon: Moon,
  Briefcase: Briefcase,
  Handshake: Handshake,
  Sparkles: Sparkles,
  Shield: Shield,
  Warning: AlertTriangle,
  Lock: Lock,
  Unlock: Unlock,
  PieChart: PieChart,
  BarChart: BarChart3,
  Help: HelpCircle
};
